name: gatsby deploy

on:
  push:
    branches: [main]

jobs:
  gatsby deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: npm install

      # - name: gatsby build
      #   run: yarn build
      #   env:
      #     GH_API_KEY: ${{ secrets.API_KEY }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.API_KEY }}
          publish_dir: 'public/'
